### ISSUE TITLE
FileNotFoundException running the docker container

### ISSUE THREAD

**Issue by asiletto** [jacopofar/italian-nlp-library#1]
I get this FileNotFoundException running the docker container:

```
java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:297)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.FileNotFoundException: database /opt/italian-nlp-library/target/classes//it_verb_model.db not found or not a file
        at com.github.jacopofar.italib.ItalianModel.<init>(ItalianModel.java:222)
        at com.github.jacopofar.italib.ItalianModel.<init>(ItalianModel.java:300)
        at com.github.jacopofar.italib.restserver.Server.main(Server.java:31)
        ... 6 more

```

**Comment by jacopofar** [comment]
For some reason I made the Docker build download the model files in the test path but not in the running one, there was also a little mistake in the POM file.

Now it's fixed, run `docker pull jacopofar/italian-nlp-library` to update your image and it will work.

Out of curiosity, what are you using it for ? I'm very curious to know

**Comment by asiletto** [comment]
I am using your project to extract tags from a feed of italian news. I am learning NLP and your tool is quite handy

thank you!
